/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#486720",
        "surface": "#fbf9f5",
        "inverse-primary": "#aed27e",
        "surface-container-high": "#eae8e4",
        "ink-primary": "#1A1915",
        "secondary-fixed-dim": "#b8d15a",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#171e00",
        "paper-subtle": "#F4F0E6",
        "primary": "#274200",
        "on-tertiary-container": "#c8c4c0",
        "accent-chartreuse": "#8EA633",
        "outline-variant": "#c4c8b8",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#53514f",
        "dark-surface": "#201F1D",
        "primary-container": "#3c5a14",
        "tertiary-fixed-dim": "#cac6c2",
        "surface-container": "#efeeea",
        "on-tertiary-fixed-variant": "#484644",
        "surface-bright": "#fbf9f5",
        "on-primary": "#ffffff",
        "primary-fixed": "#c9ef98",
        "dark-canvas": "#141311",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e2de",
        "background": "#fbf9f5",
        "on-background": "#1b1c1a",
        "tertiary": "#3c3a38",
        "inverse-surface": "#30312e",
        "tertiary-fixed": "#e6e2de",
        "on-tertiary-fixed": "#1c1b19",
        "on-primary-fixed-variant": "#324f08",
        "on-surface": "#1b1c1a",
        "secondary": "#536600",
        "secondary-fixed": "#d3ee72",
        "ink-secondary": "#636059",
        "surface-container-low": "#f5f3ef",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#acd17d",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3e4c00",
        "surface-variant": "#e4e2de",
        "inverse-on-surface": "#f2f0ed",
        "on-primary-fixed": "#102000",
        "on-surface-variant": "#44483c",
        "on-secondary-container": "#586c00",
        "primary-fixed-dim": "#aed27e",
        "accent-forest": "#3C5A14",
        "outline": "#74796a",
        "surface-dim": "#dbdad6",
        "paper-border": "#E8E4DA",
        "paper-base": "#FBF9F5",
        "secondary-container": "#d3ee72",
        "ink-muted": "#918E84",
        "paper-border-dark": "#D5CEBE"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1.25rem",
        "space-2xl": "4rem",
        "space-sm": "0.5rem",
        "margin": "3rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "button-text": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-xl-mobile": ["Newsreader", "serif"],
        "label-code": ["Space Mono", "monospace"],
        "headline-md": ["Newsreader", "serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
        "display-xl": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "label-caps": ["Space Mono", "monospace"],
        "display-lg": ["Newsreader", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Newsreader", "serif"]
      },
      fontSize: {
        "button-text": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-xl-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-md": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
